# Brand Colors
ROYAL_BLUE = '#3447AA'
POWDER_PINK = '#FBEAEB'

# Background
BACKGROUND = '#F0F0F0'

# Surfaces
SURFACE = '#FBFBFB'
SURFACE_ALT = '#FFFFFF'
SURFACE_ALT2 = '#F0F0F0'
SURFACE_ACCENT_SOFT = '#EDF2FB'
SURFACE_HOVER = '#F6F8FC'
SURFACE_HOVER_SOFT = '#EEF2FB'
SURFACE_DANGER_HOVER = '#FFF1F1'

# Number Badge
NUMBER_DESIGNATION_BG = SURFACE_HOVER

# Borders
BORDER = '#E4E8F1'
BORDER_SOFT = '#D7DEEA'
BORDER_LIGHT = '#D9DEEA'
BORDER_INPUT = '#C8D0E6'

# Text
TEXT_PRIMARY = '#222831'
TEXT_SECONDARY = '#6B7280'
TEXT_INVERSE = '#FAFAFA'
TEXT_EMPHASIS = '#1F2B4A'
TEXT_PLACEHOLDER = '#8F96AD'
TEXT_SUBTLE = '#5C667F'

# Text Accent
TEXT_TINT = '#2D3448'
TEXT_TINT_HOVER = '#2B3348'
TEXT_ON_PRIMARY_SOFT = '#F3F2FF'
TEXT_NEUTRAL_DARK = '#111111'

# Interactive
PRIMARY = ROYAL_BLUE
PRIMARY_HOVER = '#2E3F97'
PRIMARY_PRESSED = PRIMARY
PRIMARY_ACTION_HOVER = '#245BC0'

SECONDARY = '#7287E5'
SECONDARY_STRONG = '#5555D5'
SECONDARY_STRONG_HOVER = '#5E64E6'
SECONDARY_ACTIVE = '#6973FF'
SECONDARY_GLOW = '#7D86FF'
SECONDARY_GLOW_STRONG = '#9AA7FF'
SECONDARY_SOFT = '#ECE9FF'

ACCENT = POWDER_PINK

# Status
SUCCESS = '#2ca24d'
SUCCESS_STRONG = '#2E9B53'
FAILED = '#d23b3b'
FAILED_STRONG = '#D33E3E'
FAILED_HOVER = '#BF3232'
ALERT = '#FF4F00'
PROCESSING = '#2d6cdf'
STANDBY = '#000000'
ROW_SELECTED_SEPARATOR = '#7070E5'